import { Link } from "react-router-dom";

const TermsOfService = () => {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4 space-y-6">
      <div>
        <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white">Terms of Service</h2>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">Last updated: June 18, 2026</p>
      </div>

      <div className="bg-white dark:bg-dark-card rounded-2xl p-8 border border-slate-200 dark:border-dark-border space-y-6 text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900 dark:text-white">1. Acceptance of Terms</h3>
          <p>
            By creating an account or using any features of WealthifyMe, you agree to comply with and be bound by these Terms of Service. If you do not agree, you must terminate your account and cease using the platform.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900 dark:text-white">2. User Accounts</h3>
          <p>
            You are responsible for maintaining the confidentiality of your credentials and are fully responsible for all activities that occur under your account. You must notify us immediately of any unauthorized use of your credentials.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900 dark:text-white">3. Acceptable Use</h3>
          <p>
            You agree not to use the services for any illegal activities, or to inject malicious script code, or attempt to bypass auth limiters, rate limits, or payment verification webhooks. Violation of system integrity will result in permanent account suspension.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900 dark:text-white">4. Subscriptions and Billing</h3>
          <p>
            Subscription payments for Wealthify Pro are handled securely via Stripe. Payments are billed on a recurring basis. You can cancel your subscription at any time under your account Settings. Refund policies are governed by Stripe terms and local financial regulations.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900 dark:text-white">5. Disclaimer of Warranties</h3>
          <p>
            WealthifyMe is provided "as is" without warranties of any kind. We do not provide licensed financial advisory services; all metrics, charts, and budget insights generated by the platform are for informational tracking purposes only.
          </p>
        </section>
      </div>

      <div className="text-center">
        <Link to="/" className="text-xs text-slate-500 dark:text-slate-400 hover:text-teal-500 transition-colors">
          ← Back to Dashboard
        </Link>
      </div>
    </div>
  );
};

export default TermsOfService;
